#!/usr/bin/env ruby

source_path = File.dirname(__dir__)
$:.unshift(source_path)

require 'salt'

site = Salt::Site.instance
site.setup({
  use_pagination: false
})

#begin
  site.generate
#rescue Exception => e
  #puts "Error: #{e}"
#end