#!/usr/bin/env ruby

source_path = File.dirname(__dir__)
$:.unshift(source_path)

require 'salt'

config = YAML::load_file('./config.yml')
site = Salt::Site.new(config)

begin
  site.generate
rescue Exception => e
  puts "Error: #{e}"
end