#!/usr/bin/env ruby

source_path = File.dirname(__dir__)
$:.unshift(source_path)

require 'rubygems'
require 'bundler/setup'
require 'dimples'

config = YAML::load_file('config/site.yml')
site = Dimples::Site.new(config)

begin
  site.generate
rescue Exception => e
  puts "Error: #{e}"
end