name: Publish waferbaby.com

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0    
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - run: bundle exec dimples
      - uses: contention/rsync-deployments@v2.0.0
        with:
          FLAGS: -avzr --delete
          USER: deployer
          HOST: waferbaby.com
          LOCALPATH: site
          REMOTEPATH: /usr/local/share/www/waferbaby.com
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
